import {
  REST_API,
  WS_BASE
} from "../config";
// const UPLOADPATH = 'http://47.93.116.221:8000';
const UPLOADPATH = REST_API;
const WS_PATH = WS_BASE;
export default {
  wsPath: WS_PATH,
  uploadPath: UPLOADPATH,
  picPath: UPLOADPATH + "/remoteLaboratory/upload/",
  // picPath: "/Users/iamdoerzhan/Downloads/06_work/000remoteLaboratory/git/remotepic/",
  login: {
    register: `/remoteLaboratory/user/register`,
    token: `/remoteLaboratory/user/login`,
    modifyPassword: `/remoteLaboratory/user/modifyPassword`,
    admin_modifyPassword: `/remoteLaboratory/user/adminModifyPassword`,
    logout: `/remoteLaboratory/user/loginout`,
    account: `/remoteLaboratory/user/current`
  },
  index: {
    user_list: `/remoteLaboratory/user/list`,
    teacher_list: `/remoteLaboratory/user/teacherList`,
    user: `/remoteLaboratory/user`,
    import_user: `/remoteLaboratory/user/importStudent`,
    user_forumForbidden: `/remoteLaboratory/user/forumForbidden/`,
    user_modify: `/remoteLaboratory/user/modifyUserInfo`,
    device_list: `/remoteLaboratory/device/list`,
    device: `/remoteLaboratory/device`,
    signalChannel_list: `/remoteLaboratory/signalChannel/list`,
    signalChannel: `/remoteLaboratory/signalChannel`,
    camera_list: `/remoteLaboratory/camera/list`,
    camera: `/remoteLaboratory/camera`,
    srsServer_list: `/remoteLaboratory/srsServer/list`,
    srsServer: `/remoteLaboratory/srsServer`,
    sysSetting_list: `/remoteLaboratory/sysSetting/list`,
    sysSetting: `/remoteLaboratory/sysSetting`,
    getHomePageImages: `/remoteLaboratory/sysSetting/getHomePageImages`,
    getHomePageBottomImages: `/remoteLaboratory/sysSetting/getHomePageBottomImages`,

    upload_upload: `/remoteLaboratory/uploadFile/upload`,
    upload_list: `/remoteLaboratory/uploadFile/list`,
    upload_mylist: `/remoteLaboratory/uploadFile/myList`,
    upload_deleteById: `/remoteLaboratory/uploadFile/deleteById/`,
    upload_delete: `/remoteLaboratory/uploadFile`,

    course_list: `/remoteLaboratory/course/list`,
    course: `/remoteLaboratory/course`,
    course_setscore: `/remoteLaboratory/course/setScore`,
    course_getDetail: `/remoteLaboratory/course/getDetail`,
    course_setStudentGrade: `/remoteLaboratory/course/setStudentGradeSwitch/`,
    coursecomment_list: `/remoteLaboratory/courseComment/list`,
    coursecomment: `/remoteLaboratory/courseComment`,
    coursecomment_setdefault: `/remoteLaboratory/courseComment/setMainPageDisplay/`,
    updateStatus: `/remoteLaboratory/course/updateStatus/`,
    startExperiment: `/remoteLaboratory/course/startExperiment/`,
    chapter_list: `/remoteLaboratory/chapter/list`,
    chapter: `/remoteLaboratory/chapter`,
    section_list: `/remoteLaboratory/section/list`,
    section: `/remoteLaboratory/section`,
    section_start: `/remoteLaboratory/section/startStudy/`,
    section_finish: `/remoteLaboratory/section/finish/`,
    exercise_list: `/remoteLaboratory/exercise/list`,
    exercise: `/remoteLaboratory/exercise`,
    testTemplate_bySid: `/remoteLaboratory/testTemplate/getDetailBySectionId/`,
    testTemplate: `/remoteLaboratory/testTemplate`,
    testTemplate_detail: `/remoteLaboratory/testTemplate/getDetail`,
    testTemplate_list: `/remoteLaboratory/testTemplate/list`,
    courseDevice_list: `/remoteLaboratory/courseDevice/list`,
    courseDevice: `/remoteLaboratory/courseDevice`,
    courseDevice_listadd: `/remoteLaboratory/courseDevice/listAdd`,
    courseDevice_listadd2: `/remoteLaboratory/courseDevice/listAdd2`,
    courseDevice: `/remoteLaboratory/courseDevice`,
    announcement_list: `/remoteLaboratory/announcement/list`,
    announcement: `/remoteLaboratory/announcement`,
    subject_list: `/remoteLaboratory/subject/list`,
    subject: `/remoteLaboratory/subject`,
    simulation_list: `/remoteLaboratory/simulation/list`,
    simulation: `/remoteLaboratory/simulation`,
    reply_list: `/remoteLaboratory/reply/list`,
    reply: `/remoteLaboratory/reply`,

    deviceOrder_list: `/remoteLaboratory/deviceOrder/list`,
    deviceOrder: `/remoteLaboratory/deviceOrder/order/`,
    deviceOrder_getmy: `/remoteLaboratory/deviceOrder/getMy`,
    deviceOrder_getDetail: `/remoteLaboratory/deviceOrder/getOrderDeviceDetail/`,

    test_list: `/remoteLaboratory/testInstance/list`,
    test_submit: `/remoteLaboratory/testInstance/submit/`,
    test_finish: `/remoteLaboratory/testInstance/finish/`,
    test_getMy: `/remoteLaboratory/testInstance/getMy`,
    test_start: `/remoteLaboratory/testInstance/startTest/`,
    test_answer: `/remoteLaboratory/testInstance/answer`,
    test_grade: `/remoteLaboratory/testInstance/grade`,
    test_getMyByCourseId: `/remoteLaboratory/testInstance/getMyByCourseId/`,
    startTestBySectionId: `/remoteLaboratory/testInstance/startTestBySectionId/`,
    test_listByCourseId: `/remoteLaboratory/testInstance/listByCourseId/`,
    test_listByChapterId: `/remoteLaboratory/testInstance/listByChapterId/`,
    test_listBySectionId: `/remoteLaboratory/testInstance/listBySectionId/`,
    test_getDetail: `/remoteLaboratory/testInstance/getDetail/`,
    test_questionresult_getbycourseid: `/remoteLaboratory/testTemplate/getQuestionnaire`,
    test_export: `/remoteLaboratory/testInstance/exportByCourseId/`,
    test_instance_list: `/remoteLaboratory/testInstance/list`,

    test_instance_getmygrade: `/remoteLaboratory/testInstance/getMyGrade/`,
    test_instance_getonetograde: `/remoteLaboratory/testInstance/getOneToGrade/`,

    course_getmy: `/remoteLaboratory/courseStudyRecord/getMy`,
    course_detail_getmy: `/remoteLaboratory/courseStudyRecord/getMyDetailByCourseId/`,
    startStudy: `/remoteLaboratory/courseStudyRecord/startStudy/`,
    study_listByCourseId: `/remoteLaboratory/courseStudyRecord/listByCourseId/`,
    study_getMy: `/remoteLaboratory/courseStudyRecord/getMy`,

    study_statistics: `/remoteLaboratory/courseStudyRecord/getScoreStatistics`,
    class_getgradebycourseid: `/remoteLaboratory/class/getGradeByCourseId`,
    major_getbycourseid: `/remoteLaboratory/class/getMajorByCourseId`,
    grade_getbycourseid: `/remoteLaboratory/class/getGradeByCourseId`,
    class_getbycourseid: `/remoteLaboratory/class/getByCourseId`,
    major_get: `/remoteLaboratory/class/getMajor`,
    grade_get: `/remoteLaboratory/class/getGrade`,
    class_get: `/remoteLaboratory/class/getClass`,
  }
};
